import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  CookieSVG,
  DocSVG,
  HackerSVG,
  MapSVG,
  NerdSVG,
  ShieldSVG,
  SearchbarSVG,
  BrowserSVG,
  PhoneSVG,
  SlideSVG,
  SearchResultsSVG,
  VideoSVG,
} from "../public/svgs/source";
export default function Home() {
  return (
    //<div className={styles.container}>
    //  <Head>
    //    <title>Create Next App</title>
    //    <meta name="description" content="Generated by create next app" />
    //    <link rel="icon" href="/favicon.ico" />
    //  </Head>

    //  <main className={styles.main}>
    //    <h1 className={styles.title}>
    //      Welcome to <a href="https://nextjs.org">Next.js!</a>
    //    </h1>

    //    <p className={styles.description}>
    //      Get started by editing{" "}
    //      <code className={styles.code}>pages/index.js</code>
    //    </p>

    //    <div className={styles.grid}>
    //      <a href="https://nextjs.org/docs" className={styles.card}>
    //        <h2>Documentation &rarr;</h2>
    //        <p>Find in-depth information about Next.js features and API.</p>
    //      </a>

    //      <a href="https://nextjs.org/learn" className={styles.card}>
    //        <h2>Learn &rarr;</h2>
    //        <p>Learn about Next.js in an interactive course with quizzes!</p>
    //      </a>

    //      <a
    //        href="https://github.com/vercel/next.js/tree/master/examples"
    //        className={styles.card}
    //      >
    //        <h2>Examples &rarr;</h2>
    //        <p>Discover and deploy boilerplate example Next.js projects.</p>
    //      </a>

    //      <a
    //        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //        className={styles.card}
    //      >
    //        <h2>Deploy &rarr;</h2>
    //        <p>
    //          Instantly deploy your Next.js site to a public URL with Vercel.
    //        </p>
    //      </a>

    //      <Lotties />
    //      <TestComponent />
    //    </div>
    //  </main>

    //  <footer className={styles.footer}>
    //    <a
    //      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //      target="_blank"
    //      rel="noopener noreferrer"
    //    >
    //      Powered by{" "}
    //      <span className={styles.logo}>
    //        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //      </span>
    //    </a>
    //  </footer>
    //</div><
    <div>
      <div className={styles.spaceApart}>
        <h1 className={styles.searchBarTitle}>
          <span className={styles.colorBlue}>Y</span>
          <span className={styles.colorRed}>o</span>
          <span className={styles.colorYellow}>u</span>
          <span> </span>
          <span className={styles.colorBlue}>G</span>
          <span className={styles.colorGreen}>o</span>
          <span className={styles.colorRed}>o</span>
          <span className={styles.colorYellow}>g</span>
          <span className={styles.colorBlue}>l</span>
          <span className={styles.colorRed}>e</span>
          <span className={styles.colorYellow}>d</span>
        </h1>
        <div className={styles.searchBar}>
          <p className={styles.searchBarText}>Internet Privacy </p>
          <SearchbarSVG />
        </div>
      </div>

      {/*<div>
        
      </div>*/}

      <div className={styles.mainSection}>
        <div className={styles.searchResultText}>
          <h2>What is Internet Privacy</h2>
          <p>
            The level of privacy an individual has while connected to the
            internet while sharing private information with others.
          </p>
          <h2>Introduction</h2>
          <p>
            Today’s internet is a prosperous goldmine for Google. Whether users
            are browsing websites or watching videos, Google aggregates our data
            to understand human behaviors. However, is there any information
            that we don&apos;t want it to know?
          </p>
        </div>

        <SearchResultsSVG className={styles.searchResult} />

        {/*<NerdSVG />*/}
        {/*<p>
            Internet privacy takes many forms: it could be privacy regarding our
            activities on a website, sharing how much we share about ourselves,
            etc. It can be our daily sp- -lurges, our recent shopping splurges,
            and the devices we use. Ideally, we want to control the amount of
            information that flows out. However, this isn&apos;t always the case
            for companies like Google. Once on their platform, they set the
            terms and conditions on how they use the user&apos;s information. So
            there&apos;s no absolute control for individuals to decide what others
            get to see our data or not.
          </p>*/}

        {/*<div className={styles.spaceApart}>

          </div>*/}

        <div className={styles.spaceApart}>
          <h2>How Google Tracks Us</h2>
          <div>
            <h3>Gmail, Google Office Suite, Google Photo</h3>
            <p className={styles.docText}>
              Any documents created on with Gmail or Google Office Suite are
              scanned with Google Analytic. The tools algorithm will aggregate
              the words from the document to be used with personalized ads.
            </p>
            <DocSVG className={styles.document} />
          </div>

          <div>
            <h3>Google Chrome</h3>
            {/*<CookieSVG />*/}
            <p className={styles.docText}>
              The main way Chrome tracks you is through cookies that contains
              data used to identify our computer. Its a way for the service to
              identify your computer which includes the IP address, log-in info,
              operating system, screen size, mouse movements, etc.{" "}
            </p>
            <BrowserSVG className={styles.document} />
          </div>

          <div>
            <h3>Android Phone</h3>
            <MapSVG />
            <p>
              Location tracking is a common method Google keep track of our
              movement. The GPS feature on the smartphone provides Google a
              better understanding on our habits and the location we last
              visited. The data is used on GoogleMap to influence our behavior
              by creating suggestions.
            </p>
          </div>
        </div>

        <div className={styles.spaceApart}>
          <h2>What Does Google Do with Our Data</h2>
          <p className={styles.slideText}>
            Google&apos;s policy ensures that users&apos; data to be not sold to
            third-party vendors. It does, however, use our data for personalized
            adverts. Advertisers can customize their campaigns to their targeted
            audience. Once matched, targeted adverts will appear on websites to
            encourage users to explore their products. Other Google services
            benefit from collecting your data. Google internet of things (IoT)
            devices are dependent on your data to customize your experience.
            Including recorded audio that Home needs to continue to listen to
            the user&apos;s conversation. To Google, their design philosophy is
            keen to make your experience the best on their platform. And they
            want you, a consumer, to continue to use their apps for the ind
            efinite future. But your privacy still matters as a consumer whose
            data can still be vulnerable. Blindly accepting terms and conditions
            can present us with a dangerous situation. Your data can hold
            valuable assets for others to pluck from the company&apos;s network.
          </p>
          <SlideSVG className={styles.powerSlide} />
        </div>

        <div className={styles.spaceApart}>
          <h2>Digital Security and Your Data</h2>
          <p className={styles.videoText}>
            Between 2012 - 2017 major breaches were done by hackers. User&apos;s
            data were compromised where it can be used misused or disclosed
            without consent. Hackers use different types of tactics for
            installing malicious malware. In 2013, Target suffered a breach
            where hackers were able to obtain a vendor&apos;s key. The hackers
            installed malware where it can retrieve a user&apos;s credit and
            debit card information. Yahoo also reported a data breach affecting
            3 billion users in 2016. The hacker obtained the user&apos;s name,
            email address, phone numbers, date of birth, hashed passwords, and
            security questions and answers.
          </p>
          <VideoSVG />
        </div>

        <div>
          <h2>Protecting Ourselves Online</h2>
          <ShieldSVG />
          <p>
            It&apos;s important to limit how much information we provide to a
            big company. The overreliance on the platform can come to a point
            where an unauthorized actor obtains our data. Google provides a
            dashboard to allow users to customize what data they want to
            opt-out. Another solution is to use other alternative platforms with
            similar services. On the internet, there&apos;s no absolute way to
            abstain from using online services. We can, however, protect
            ourselves by understanding what information we are willing to
            provide. Internet privacy is about controlling what information we
            want to show rather than show it all.
          </p>
        </div>
      </div>
    </div>
  );
}
