import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  CookieSVG,
  DocSVG,
  HackerSVG,
  MapSVG,
  NerdSVG,
  ShieldSVG,
} from "../public/svgs/source";
export default function Home() {
  return (
    //<div className={styles.container}>
    //  <Head>
    //    <title>Create Next App</title>
    //    <meta name="description" content="Generated by create next app" />
    //    <link rel="icon" href="/favicon.ico" />
    //  </Head>

    //  <main className={styles.main}>
    //    <h1 className={styles.title}>
    //      Welcome to <a href="https://nextjs.org">Next.js!</a>
    //    </h1>

    //    <p className={styles.description}>
    //      Get started by editing{" "}
    //      <code className={styles.code}>pages/index.js</code>
    //    </p>

    //    <div className={styles.grid}>
    //      <a href="https://nextjs.org/docs" className={styles.card}>
    //        <h2>Documentation &rarr;</h2>
    //        <p>Find in-depth information about Next.js features and API.</p>
    //      </a>

    //      <a href="https://nextjs.org/learn" className={styles.card}>
    //        <h2>Learn &rarr;</h2>
    //        <p>Learn about Next.js in an interactive course with quizzes!</p>
    //      </a>

    //      <a
    //        href="https://github.com/vercel/next.js/tree/master/examples"
    //        className={styles.card}
    //      >
    //        <h2>Examples &rarr;</h2>
    //        <p>Discover and deploy boilerplate example Next.js projects.</p>
    //      </a>

    //      <a
    //        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //        className={styles.card}
    //      >
    //        <h2>Deploy &rarr;</h2>
    //        <p>
    //          Instantly deploy your Next.js site to a public URL with Vercel.
    //        </p>
    //      </a>

    //      <Lotties />
    //      <TestComponent />
    //    </div>
    //  </main>

    //  <footer className={styles.footer}>
    //    <a
    //      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //      target="_blank"
    //      rel="noopener noreferrer"
    //    >
    //      Powered by{" "}
    //      <span className={styles.logo}>
    //        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //      </span>
    //    </a>
    //  </footer>
    //</div><
    <div>
      <div>
        <h1>You Googled</h1>
        <div>
          <svg></svg>
        </div>
      </div>
      <article>
        <article>
          <h2>Introduction</h2>
          <p>
            Today’s internet is a prosperous goldmine for Google. Whether users
            are browsing websites or watching videos, Google aggregates our data
            to understand human beh- -aviors. However, is there any information
            that we don&#39at want it to know?
          </p>
        </article>

        <article>
          <h2>What is Internet Privacy</h2>
          <NerdSVG />
          <p>
            Internet privacy takes many forms: it could be privacy regarding our
            activities on a website, sharing how much we share about ourselves,
            etc. It can be our daily sp- -lurges, our recent shopping splurges,
            and the devices we use. Ideally, we want to control the amount of
            information that flows out. However, this isn&#39t always the case
            for companies like Google. Once on their platform, they set the
            terms and conditions on how they use the user&#39s information. So
            there&#39s no absolute control for individuals to decide what others
            get to see our data or not.
          </p>
        </article>

        <article>
          <h2>How Google Tracks Us</h2>
          <article>
            <h3>Gmail, Google Office Suite, Google Photo</h3>
            <DocSVG />
            <p>
              Any documents created on with Gmail or Google Office Suite are
              scanned with Google Analytic. The tools algorithm will aggregate
              the words from the document to be used with personalized ads.
            </p>
          </article>

          <article>
            <h3>Google Chrome</h3>
            <CookieSVG />
            <p>
              The main way Chrome tracks you is through cookies that contains
              data used to identify our computer. Its a way for the service to
              identify your computer which includes the IP address, log-in info,
              opera- -ting system, screen size, mouse movements, etc.{" "}
            </p>
          </article>

          <article>
            <h3>Android Phone</h3>
            <MapSVG />
            <p>
              Location tracking is a common method Google keep track of our
              movement. The GPS feature on the smartphone provides Google a
              better understanding on our habits and the location we last
              visited. The data is used on GoogleMap to influence our behavior
              by creating suggestions.
            </p>
          </article>
        </article>

        <article>
          <h2>What Does Google Do with Our Data</h2>
          <p>
            Google&#39s policy ensures that users&#39 data to be not sold to
            third-party vendors. It does, however, use our data for personalized
            adverts. Advertisers can customize t- heir campaigns to their
            targeted audience. Once matched, targeted adverts will ap- pear on
            websites to encourage users to explore their products. Other Google
            servi- ces benefit from collecting your data. Google internet of
            things (IoT) devices are dependent on your data to customize your
            experience. Including recorded audio that Home needs to continue to
            listen to the user&#39s conversation. /n To Google, their design
            philosophy is keen to make your experience the best on their
            platform. And they want you, a consumer, to continue to use their
            apps for the ind- efinite future. But your privacy still matters as
            a consumer whose data can still be vulnerable. Blindly accepting
            terms and conditions can present us with a dangerous situation. Your
            data can hold valuable assets for others to pluck from the
            company&#39s network.
          </p>
        </article>

        <article>
          <h2>Digital Security and Your Data</h2>
          <HackerSVG />
          <p>
            Between 2012 - 2017 major breaches were done by hackers. User&#39s
            data were compromi- -sed where it can be used misused or disclosed
            without consent. Hackers use differ- -ent types of tactics for
            installing malicious malware. In 2014, Home Depot suffered a breach
            when an unauthorized third party got hold of a vendor&#39s password.
            The files stolen were 56 million email addresses but are susceptible
            to phishing scams. In addition, the hackers can navigate a portion
            of the Home Depot network to install customizable malware. The same
            happened to Target in 2013, where hackers were able to obtain a
            vendor&#39s key. The hackers installed malware where it can retrieve
            a user&#39s credit and debit card information. Yahoo also reported a
            data breach affecting 3 billion users in 2016. The hacker obtained
            the user&#39s name, email address, phone numbers, date of birth,
            hashed passwords, and security questions and answers. Aleksey Belan
            spear- phished emails to Yahoo company employees to gain access to
            their network. Once clicked on the link, Belan installed a backdoor
            for himself and his colleagues to download the database and account
            management tool.
          </p>
        </article>

        <article>
          <h2>Protecting Ourselves Online</h2>
          <ShieldSVG />
          <p>
            It&#39s important to limit how much information we provide to a big
            company. The over- -reliance on the platform can come to a point
            where an unauthorized actor obtains our data. Google provides a
            dashboard to allow users to customize what data they want to
            opt-out. Another solution is to use other alternative platforms with
            sim- -ilar services. On the internet, there&#39s no absolute way to
            abstain from using online services. We can, however, protect
            ourselves by understanding what infor- -mation we are willing to
            provide. Internet privacy is about controlling what in- -formation
            we want to show rather than show it all.
          </p>
        </article>
      </article>
    </div>
  );
}
